# Generated by Django 2.1.7 on 2019-04-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speaker_icon2',
            field=models.ImageField(blank=True, upload_to='speaker'),
        ),
    ]
