# Generated by Django 2.1.7 on 2019-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_speaker_icon2'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_short_session',
            field=models.BooleanField(default=False),
        ),
    ]
